[theme]
primaryColor = "#007aff"      # Apple Blau
backgroundColor = "#ffffff"   # Weiß
secondaryBackgroundColor = "#f5f5f7"  # Apple Light Gray
textColor = "#000000"         # Schwarz
font = "sans serif"
