[theme]
base = "dark"                         # <- Dark Mode aktivieren
primaryColor = "#0A84FF"              # Apple Blue
backgroundColor = "#252a3bff"           # App-Hintergrund
secondaryBackgroundColor = "#313a52ff"  # Cards/Sidebar
textColor = "#F5F7FA"
font = "sans serif"
